// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLBio0Dlhj_pjPMzvi8BOxA7_-Myx8iEk',
    appId: '1:157417127240:web:f2fb8df42ba0aedadf477d',
    messagingSenderId: '157417127240',
    projectId: 'fir-sample-a1d89',
    authDomain: 'fir-sample-a1d89.firebaseapp.com',
    storageBucket: 'fir-sample-a1d89.firebasestorage.app',
    measurementId: 'G-891XNS30G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaST1_pmVHB_86vL9Hcncug9-EgeXRX9I',
    appId: '1:157417127240:android:e8901731da3050badf477d',
    messagingSenderId: '157417127240',
    projectId: 'fir-sample-a1d89',
    storageBucket: 'fir-sample-a1d89.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh7OzzkBVy7pWuhkioGQDiR-wlDqjp90Y',
    appId: '1:157417127240:ios:133b718e8bbcf09edf477d',
    messagingSenderId: '157417127240',
    projectId: 'fir-sample-a1d89',
    storageBucket: 'fir-sample-a1d89.firebasestorage.app',
    iosBundleId: 'com.example.mainProjectUi',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh7OzzkBVy7pWuhkioGQDiR-wlDqjp90Y',
    appId: '1:157417127240:ios:133b718e8bbcf09edf477d',
    messagingSenderId: '157417127240',
    projectId: 'fir-sample-a1d89',
    storageBucket: 'fir-sample-a1d89.firebasestorage.app',
    iosBundleId: 'com.example.mainProjectUi',
  );

}